resource_types:
- name: slack-notification
  type: docker-image
  source:
    repository: cfcommunity/slack-notification-resource
    tag: v1.4.2

resources:
- name: wekan-staging
  type: cf
  icon: cloud-upload
  source:
    api: ((cf.api))
    username: ((cf.username))
    password: ((cf.password))
    organization: ((cf.org))
    space: ((cf.space))
    skip_cert_check: false

- name: seronet-wekan
  type: git
  icon: github-face
  source:
    uri: git@github.com:seronet-project/wekan.git
    branch: master
    depth: 5
    disable_ci_skip: false
    private_key: ((github-private-key))

- name: wekan-wekan
  type: git
  icon: github-face
  source:
    uri: https://github.com/wekan/wekan.git
    branch: master
    depth: 30

- name: notify
  type: slack-notification
  icon: chat-alert
  source:
    url: ((slack-webhook))

- name: merge-timer
  type: time
  source:
    start: 2:30 AM
    stop: 3:30 AM
    location: Europe/Berlin

jobs:
- name: merge-wekan
  public: false
  serial_groups: ["wekan"]
  plan:
  - get: merge-timer
    trigger: true
  - get: wekan-wekan
#    trigger: true
  - get: seronet-wekan
  - task: merge-wekan-master
    config:
      platform: linux
      inputs:
      - name: seronet-wekan
      outputs:
      - name: seronet-wekan
      image_resource:
        type: docker-image
        source:
          repository: cloudfoundry/cflinuxfs3
      run:
        path: bash
        args:
        - -exc
        - |
          cd seronet-wekan
          git config user.email "concourse@sero.network"
          git config user.name "SeRoNet Concourse"
          git remote add wekan https://github.com/wekan/wekan.git
          git fetch wekan master
          git merge --no-edit wekan/master
  - put: seronet-wekan
    params:
      repository: seronet-wekan

- name : deploy-wekan
  serial_groups: ["wekan"]
  plan:
    - get: seronet-wekan
      trigger: true
    - task: wekan-prebuild
      config:
        platform: linux
        inputs:
          - name: seronet-wekan
        outputs:
          - name: wekan-out
          - name: wekan-build
        image_resource:
          type: docker-image
          source:
            repository: node
            tag: 12.18.3
        run:
          user: root
          path: sh
          args:
          - -exc
          - |
            command -v meteor >/dev/null 2>&1 || curl https://install.meteor.com | sed s/--progress-bar/-sL/g | /bin/sh
            # apt-get update && apt-get install -y build-essential nvi
            node -v
            export METEOR_ALLOW_SUPERUSER=true
            meteor --version
            cp -r seronet-wekan/. wekan-build
            cd wekan-build
            meteor npm install
            meteor build --server-only --directory ../wekan-out
            cp -f fix-download-unicode/cfs_access-point.txt ../wekan-out/bundle/programs/server/packages/cfs_access-point.js
            cp .concourse/manifest.yml ../wekan-out
            cd ../wekan-out
            node -v > bundle/.nvmrc
            ls bundle
            cd bundle/programs/server
            rm -rf node_modules
            meteor npm install
            cd -
            chmod -R u+rw bundle
    - put: wekan-staging
      params:
        manifest: wekan-out/manifest.yml
        environment_variables:
          OAUTH2_ENABLED: "true"
          OAUTH2_LOGIN_STYLE: redirect
          OAUTH2_CLIENT_ID: ((oidc.id))
          OAUTH2_SECRET: ((oidc.secret))
          OAUTH2_SERVER_URL: ((oidc.url))
          OAUTH2_AUTH_ENDPOINT: /realms/((oidc.realm))/protocol/openid-connect/auth
          OAUTH2_USERINFO_ENDPOINT: /realms/((oidc.realm))/protocol/openid-connect/userinfo
          OAUTH2_TOKEN_ENDPOINT: /realms/((oidc.realm))/protocol/openid-connect/token
          OAUTH2_ID_MAP: sub
          OAUTH2_USERNAME_MAP: preferred_username
          OAUTH2_FULLNAME_MAP: given_name
          OAUTH2_EMAIL_MAP: email
          OAUTH2_REQUEST_PERMISSIONS: 'openid profile email roles'
      on_success:
        put: notify
        params:
          text: "Wekan deployed."
      on_failure:
        put: notify
        params:
          text: "Wekan deployment failed." 
